# Generated by Django 2.0.3 on 2018-04-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestScrapy',
            fields=[
                ('iAutoId', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=1024)),
            ],
            options={
                'db_table': 'dg_spider_django1',
            },
        ),
    ]
